### ISSUE TITLE
how can i get the pyedb

### ISSUE THREAD

**Issue by Jerry0427** [MarkBaggett/ese-analyst#2]
i can’t use pip to get pyedb

**Comment by Jerry0427** [comment]
pyesedb

**Comment by MarkBaggett** [comment]
The name of the package is libesedb-python and it is not easy to install.
Instructions for doing so are on the readme on SRUM_DUMP (
https://github.com/MarkBaggett/srum-dump) .    To make your life easier  I
have distributed an EXE that you can just download and run.

Mark

**Comment by Jerry0427** [comment]
> The name of the package is libesedb-python and it is not easy to install. Instructions for doing so are on the readme on SRUM_DUMP ( https://github.com/MarkBaggett/srum-dump) . To make your life easier I have distributed an EXE that you can just download and run. Mark
> […](

Thank you very much

**Comment by Jerry0427** [comment]
I am a chinese student.I want to use a part of your code to make a useful tool ，and use this tool to take part in a competition.Can i do it？

**Comment by MarkBaggett** [comment]
Sure.  As long as it isn’t sold commercially. 

Mark
