### ISSUE TITLE
Windows Compatibility

### ISSUE THREAD

**Issue by oasec1** [MarkBaggett/ese-analyst#6]
I'm getting a windows compatibility error when running ese2csv.exe  under a Windows 11 command prompt.  It says this app cant run on your pc. To find a version for your PC Check with the softwware publisher.

Is there a compatible version?

Thanks
Robert

**Comment by MarkBaggett** [comment]
I just downloaded it and ran it on my windows 11 machine.  You might check the hash.
```
PS C:\Users\lo127\Downloads> .\ese2csv.exe
usage: ese2csv.exe [-h] [--make-plugin]
                   [--pluggin {No Plugins found in path C:\Users\lo127\Downloads\ese2csv.exe}]
                   [--outpath OUTPATH] [--acquire-live] [--verbose]
                   [--list-tables] [--recurse]
                   [--dump-tables [DUMPTABLES [DUMPTABLES ...]]]
                   [--plugin-args [PLUGINARGS [PLUGINARGS ...]]]
                   ese_file
ese2csv.exe: error: the following arguments are required: ese_file
PS C:\Users\lo127\Downloads> Get-FileHash -Algorithm sha512 .\ese2csv.exe

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA512          AD786B258293ED665E8AE53E4777155B69E9E87DD538D7CB4B562515B60135EE3C6... C:\Users\lo127\Downloads\ese2...
```

**Comment by oasec1** [comment]
Mark,

Thanks for the fast response. I'll check the hash, here is the  commandline I was running.
ese2csv.exe -p srudb_plugin -a --plugin-args c:\users\robert\Desktop\SOFTWARE -- C:\Users\Robert\Desktop\SRUDB.dat

Robert

**Comment by oasec1** [comment]
Thanks for the help. You can disregard the error was resolved by correcting the commandline.

Robert
